exporter:
  config:
    volumeName: nginx-exporter-config-volume
    configMapName: nginx-exporter-config
    mountPath: /etc/nginx-exporter/exporter.conf
    subPath: exporter.conf
  image:
    repository: nginx/nginx-exporter
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 9113
  livenessProbe:
    path: /metrics
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    path: /metrics
    initialDelaySeconds: 15
    periodSeconds: 10
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

nginx:
  config:
    volumeName: nginx-config-volume
    configMapName: nginx-config
    mountPath: /etc/nginx/nginx.conf
    subPath: nginx.conf
  image:
    repository: nginx
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 80
  livenessProbe:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

